### PR TITLE
Optional indicator

### PR DESCRIPTION
**Pull request by joeyballentine**
image

### CODE REVIEW

**Comment by RunDevelopment** [comment]
I agree that some indicator is necessary, but I would have done it the other way around. Most inputs are required, so I think we should indicate that some fields are optional instead.

**Comment by joeyballentine** [comment]
That makes sense, but idk how to show something is optional. I can't think of any standard way of showing that

**Comment by joeyballentine** [comment]
image

**Comment by RunDevelopment** [comment]
Could you merge main into this, so I can see what you changed again?

**Comment by joeyballentine** [comment]
> Could you merge main into this, so I can see what you changed again?

I did already

**Comment by RunDevelopment** [comment]
You branched this from `type-colors-big-redesign`, right? If so, then the only way I know to solve this is to merge `main` into `type-colors-big-redesign`, and then `type-colors-big-redesign` into this branch.

**Comment by joeyballentine** [comment]
The diff seems perfectly normal to me, you should try refreshing or something

**Comment by RunDevelopment** [comment]
Then why did `package-lock.json` change so much?

**Comment by joeyballentine** [comment]
> Then why did `package-lock.json` change so much?

I ran npm audit fix

**Comment by RunDevelopment** [comment]
> I ran npm audit fix

... 
This is why `npm audit fix`es are typically separate PRs.

**Review by RunDevelopment — APPROVED** [review]
Anyway, LGTM;

**Pull request merged**
