### PR TITLE
Discord RPC Integration

### PR DESCRIPTION
**Pull request by BigBoyBarney**
A rudimentary Discord Rich Presence integration.
New PR because the last one is scuffed now

### CODE REVIEW

**Comment by theflyingzamboni** [comment]
@BigBoyBarney You should just be able to change the target of the other PR to main to fix it.

**Comment by BigBoyBarney** [comment]
I just realised this PR reverts a shitton of stuff so I messed something up. LOL 
I changed the target of the other PR to main and Settingsmodal.tsx still conflicts

**Comment by joeyballentine** [comment]
@theflyingzamboni since I rebased it thinks all those commits are different from the ones in main, so it's not that easy. Barney has to rebase properly for it to work right

**Comment by theflyingzamboni** [comment]
Ah, RIP

**Comment by joeyballentine** [comment]
Replaced by #897

**Pull request closed without merging**
