### PR TITLE
Fix PYTHONHOME variable deletion causing crash

### LINKED ISSUE #749: after installed the 0.11.1 exe on windows,failed to fetch

### LINKED ISSUE #752: critical error - failed to fetch with ChaiNNER 0.11.1 on Mac OS 10.14.6 Mojave
"chaiNNer  - has encountered a critical error - failed to fetch" error message.

I clicked "allow" network collection.
After downloading app components and loading dependencies etc
A screen opened with an error message.
Screenshot 2022-08-18 at 16 32 41

### PR DESCRIPTION
**Pull request by joeyballentine**
For sure fixes #752 and fixes #749. Might fix the others as well, but I'm not entirely sure.

### CODE REVIEW

**Comment by RunDevelopment** [comment]
Could you explain what this does?

**Comment by joeyballentine** [comment]
> 

#583. Turns out the fix only works when the variable exists, otherwise it crashes

**Comment by RunDevelopment** [comment]
That doesn't make any sense. If you delete a key that doesn't exist in the object, then [`delete` won't do anything](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete). So why does it crash?

**Comment by joeyballentine** [comment]
You're right. I just retested it and it turns out this does nothing. I must have accidentally switched between doing npm run dev and npm start, because run dev still crashes like that (but start doesn't)

**Pull request closed without merging**
