### PR TITLE
Add toggle for checking for an update on startup

### PR DESCRIPTION
**Pull request by JumpyJacko**

### CODE REVIEW

**Comment by joeyballentine** [comment]
Can you set this PR to be to the v0.12.0 branch? Also can you rebase so that it doesn't have your edge detection stuff in it? Thanks

**Comment by JumpyJacko** [comment]
> Can you set this PR to be to the v0.12.0 branch? Also can you rebase so that it doesn't have your edge detection stuff in it? Thanks

Can you please point me towards how to rebase? I haven't worked with a team with git before.

**Comment by theflyingzamboni** [comment]
> Can you please point me towards how to rebase? I haven't worked with a team with git before.

Are you using VS Code, or something else?

**Comment by joeyballentine** [comment]
@JumpyJacko I fixed it for you, if you don't mind me pushing directly to this branch

**Comment by JumpyJacko** [comment]
> @JumpyJacko I fixed it for you, if you don't mind me pushing directly to this branch

Yep, thats fine for me!

**Pull request merged**
